---
# call role mediatum

- name: deploy MediaTUM with deps
  hosts: "{{ group }}"
  vars:
    group: mediatum
  vars_files:
    - secret_passwords.yml
  sudo: yes
  roles:
    - mediatum

# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
