---
# defaults for the DB role
# if you want to override these variables, do it in group_vars/all
mediatum_db_name: mediatum # also defined in role defauls for mediatum
mediatum_db_user: mediatum # also defined in role defauls for mediatum

# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
